language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py27-pep8
  - TOXENV=py27-pyflakes
  - TOXENV=py27-coverage
install:
  - pip install tox --use-mirrors
  - pip install coveralls --use-mirrors
script:
  tox
after_success:
  coveralls --verbose
